server:
  port: 8088
eureka:
  client:
     serviceUrl:
       defaultZone: http://192.168.31.22:8761/eureka/
spring: 
   rabbitmq:
      host: 192.168.31.39
      port: 5672
      username: guest
      password: guest
zuul: 
  routes: 
    api:
       path: /api/**
       serviceId: api
api: 
   ribbon:
      listOfServers: http://192.168.31.22:8081/,http://192.168.31.22:8082/
management:
  security:
    enabled: false
    
