server:
  port: 8002
eureka:
  client:
     serviceUrl:
       defaultZone: http://192.168.31.173:8761/eureka/
spring: 
   rabbitmq:
      host: 192.168.31.39
      port: 5672
      username: guest
      password: guest
   sleuth:
      sampler:
        percentage: 1.0
hystrix:
  config:
    stream:
      maxConcurrentConnections: 50
