server:
  port: 8002
eureka:
  client:
     serviceUrl:
       defaultZone: http://192.168.31.173:8761/eureka/
spring: 
   rabbitmq:
      host: 192.168.31.39
      port: 5672
      username: guest
      password: guest
   zipkin:
      base-url: http://localhost:9411
   sleuth:
      sampler:
        percentage:1.0
