server:
  port: 8082
eureka:
  client:
     serviceUrl:
       defaultZone: http://192.168.31.22:8761/eureka/
spring: 
   rabbitmq:
      host: 192.168.31.39
      port: 5672
      username: guest
      password: guest
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000 
zuul:
  host: 
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
